// <auto-generated />
using System;
using BazresiApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BazresiApi.Migrations
{
    [DbContext(typeof(BazresiDb))]
    [Migration("20240909144508_user_management")]
    partial class user_management
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BazresiApi.Customized.CustomUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BazresiApi.Models.T_AdminApp", b =>
                {
                    b.Property<int>("ID_T_Admin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_T_Admin"));

                    b.Property<string>("Create_Datetime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Dateupdate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ID_T_AdminApp")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("T_Admin_Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("T_Admin_Mobail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("T_Admin_Name_Family")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("T_Admin_company")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("T_AdminsBackups_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("Types")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Vaziyat_Noskheh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_T_Admin");

                    b.ToTable("admin");
                });

            modelBuilder.Entity("BazresiApi.Models.T_Barname_Bazresi", b =>
                {
                    b.Property<long>("ID_Barname_Bazresi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID_Barname_Bazresi"));

                    b.Property<string>("DateCreate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ID_Barname_BazresiApp")
                        .HasColumnType("int");

                    b.Property<int?>("Is_Active")
                        .HasColumnType("int");

                    b.Property<int?>("Is_Completed")
                        .HasColumnType("int");

                    b.Property<long?>("T_AdminsBackups_ID")
                        .HasColumnType("bigint");

                    b.Property<int?>("T_Bazres_Id")
                        .HasColumnType("int");

                    b.Property<string>("T_Bazres_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("T_Ferekans_Item_Bazresi_Id")
                        .HasColumnType("int");

                    b.Property<string>("T_Ferekans_Item_Bazresi_Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("T_Item_Bazresi_Id")
                        .HasColumnType("int");

                    b.Property<string>("T_Item_Bazresi_Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("T_L_Vahed_Id")
                        .HasColumnType("int");

                    b.Property<string>("T_L_Vahed_Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Vaziat_Bazresi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Zaman_Bazresi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Barname_Bazresi");

                    b.ToTable("BarnameBazresi");
                });

            modelBuilder.Entity("BazresiApi.Models.T_Bazres", b =>
                {
                    b.Property<long>("ID_Bazres")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID_Bazres"));

                    b.Property<string>("Code_Meli")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DateCreate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ID_BazresApp")
                        .HasColumnType("int");

                    b.Property<int?>("Is_Active")
                        .HasColumnType("int");

                    b.Property<string>("MadrakTahsili")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name_Family")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Shomare_Personeli")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("T_AdminsBackups_ID")
                        .HasColumnType("bigint");

                    b.Property<int?>("T_L_SabegheKar_Id")
                        .HasColumnType("int");

                    b.Property<string>("T_L_Title_SabegheKar")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VahedHayBazresi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("passwordBazres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("phoneNumberBazres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("userNameBazres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Bazres");

                    b.ToTable("Bazres");
                });

            modelBuilder.Entity("BazresiApi.Models.T_Bazres_Vahed", b =>
                {
                    b.Property<long>("ID_Bazres_Vahed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID_Bazres_Vahed"));

                    b.Property<string>("DateCreate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ID_Bazres_VahedApp")
                        .HasColumnType("int");

                    b.Property<int?>("Is_Active")
                        .HasColumnType("int");

                    b.Property<long?>("T_AdminsBackups_ID")
                        .HasColumnType("bigint");

                    b.Property<int?>("T_Bazres_Id")
                        .HasColumnType("int");

                    b.Property<string>("T_Bazres_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("T_L_Vahed_Id")
                        .HasColumnType("int");

                    b.Property<string>("T_L_Vahed_Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Bazres_Vahed");

                    b.ToTable("BazresVahed");
                });

            modelBuilder.Entity("BazresiApi.Models.T_Bazresi_Azmon", b =>
                {
                    b.Property<long>("ID_Bazresi_Azmon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID_Bazresi_Azmon"));

                    b.Property<string>("DateCreate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ID_Bazresi_AzmonApp")
                        .HasColumnType("int");

                    b.Property<int?>("Is_Active")
                        .HasColumnType("int");

                    b.Property<int?>("Is_Temp")
                        .HasColumnType("int");

                    b.Property<string>("RouteVoice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("T_AdminsBackups_ID")
                        .HasColumnType("bigint");

                    b.Property<int?>("T_Bazres_Id")
                        .HasColumnType("int");

                    b.Property<int?>("T_Ferekans_Item_Bazresi_Id")
                        .HasColumnType("int");

                    b.Property<int?>("T_Item_Bazresi_Id")
                        .HasColumnType("int");

                    b.Property<int?>("T_L_Class_Item_Id")
                        .HasColumnType("int");

                    b.Property<int?>("T_L_Vahed_Id")
                        .HasColumnType("int");

                    b.Property<int?>("T_L_Zir_Class_Item_Id")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotoalScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tozihat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vaziat_Nomre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Bazresi_Azmon");

                    b.ToTable("BazresiAzmon");
                });

            modelBuilder.Entity("BazresiApi.Models.T_Bazresi_Azmon_Pic", b =>
                {
                    b.Property<long>("ID_Bazresi_Azmon_Pic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID_Bazresi_Azmon_Pic"));

                    b.Property<int?>("ID_Bazresi_Azmon_PicApp")
                        .HasColumnType("int");

                    b.Property<int?>("Is_Temp")
                        .HasColumnType("int");

                    b.Property<string>("Name_Pic")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Route_Pic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("T_AdminsBackups_ID")
                        .HasColumnType("bigint");

                    b.Property<int?>("T_Bazresi_Azmon_Id")
                        .HasColumnType("int");

                    b.HasKey("ID_Bazresi_Azmon_Pic");

                    b.ToTable("BazresiAzmonPic");
                });

            modelBuilder.Entity("BazresiApi.Models.T_Bazresi_CheckList_OK", b =>
                {
                    b.Property<long>("ID_Bazresi_CheckList_OK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID_Bazresi_CheckList_OK"));

                    b.Property<string>("DateCreate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ID_Bazresi_CheckList_OKApp")
                        .HasColumnType("int");

                    b.Property<int?>("Is_Moshkel")
                        .HasColumnType("int");

                    b.Property<int?>("Is_Temp")
                        .HasColumnType("int");

                    b.Property<decimal?>("Natijeh_Number")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Natijeh_Text")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("T_AdminsBackups_ID")
                        .HasColumnType("bigint");

                    b.Property<int?>("T_Bazresi_Azmon_Id")
                        .HasColumnType("int");

                    b.Property<int?>("T_CheckList_Id")
                        .HasColumnType("int");

                    b.Property<string>("T_Soalat_CheckList_Onvan_Soal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID_Bazresi_CheckList_OK");

                    b.ToTable("BazresiCheckList");
                });

            modelBuilder.Entity("BazresiApi.Models.T_CheckList", b =>
                {
                    b.Property<long>("ID_CheckList")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID_CheckList"));

                    b.Property<string>("DateCreate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ID_CheckListApp")
                        .HasColumnType("int");

                    b.Property<int?>("Is_Active")
                        .HasColumnType("int");

                    b.Property<string>("Onvan_CheckList")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("T_AdminsBackups_ID")
                        .HasColumnType("bigint");

                    b.Property<int?>("T_Ferekans_Item_Bazresi_Id")
                        .HasColumnType("int");

                    b.Property<string>("T_Ferekans_Item_Bazresi_Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("T_Item_Bazresi_Id")
                        .HasColumnType("int");

                    b.Property<string>("T_Item_Bazresi_Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("T_L_Class_Item_Id")
                        .HasColumnType("int");

                    b.Property<string>("T_L_Title_Zir_Class_Item")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("T_L_Titles_Class_Item")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("T_L_Titles_Vahed")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("T_L_Vahed_Id")
                        .HasColumnType("int");

                    b.Property<int?>("T_L_Zir_Class_Item_Id")
                        .HasColumnType("int");

                    b.Property<int?>("T_Ravesh_Item_Bazresi_Id")
                        .HasColumnType("int");

                    b.Property<string>("T_Ravesh_Item_Bazresi_Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID_CheckList");

                    b.ToTable("CheckList");
                });

            modelBuilder.Entity("BazresiApi.Models.T_Eghdam_Eslahi", b =>
                {
                    b.Property<long>("ID_Eghdam_Eslahi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID_Eghdam_Eslahi"));

                    b.Property<int?>("Code_Eghdam_Eslahi")
                        .HasColumnType("int");

                    b.Property<string>("DateCreate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ID_Eghdam_EslahiApp")
                        .HasColumnType("int");

                    b.Property<int?>("Is_Active")
                        .HasColumnType("int");

                    b.Property<int?>("Is_Temp")
                        .HasColumnType("int");

                    b.Property<string>("Masol_Ejra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Onvan_Eghdam_Eslahi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Route_Voice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sharh_Eghdam_Eslahi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("T_AdminsBackups_ID")
                        .HasColumnType("bigint");

                    b.Property<int?>("T_Bazresi_Azmon_Id")
                        .HasColumnType("int");

                    b.Property<int?>("T_Item_Bazresi_Id")
                        .HasColumnType("int");

                    b.Property<int?>("T_L_Class_Item_Id")
                        .HasColumnType("int");

                    b.Property<int?>("T_L_Vahed_Id")
                        .HasColumnType("int");

                    b.Property<int?>("T_L_Vaziat_Ejra_Id")
                        .HasColumnType("int");

                    b.Property<int?>("T_L_Zir_Class_Item_Id")
                        .HasColumnType("int");

                    b.Property<int?>("T_Sharh_Moshkelat_Bazresi_Id")
                        .HasColumnType("int");

                    b.Property<string>("Vaziat_Ejra_Text")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Zaman_Aghaz")
                        .HasColumnType("int");

                    b.Property<int?>("Zaman_Payan")
                        .HasColumnType("int");

                    b.HasKey("ID_Eghdam_Eslahi");

                    b.ToTable("EghdamEslahi");
                });

            modelBuilder.Entity("BazresiApi.Models.T_Ferekans_Item_Bazresi", b =>
                {
                    b.Property<long>("ID_Ferekans_Item_Bazresi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID_Ferekans_Item_Bazresi"));

                    b.Property<int?>("ID_Ferekans_Item_BazresiApp")
                        .HasColumnType("int");

                    b.Property<int?>("Is_Active")
                        .HasColumnType("int");

                    b.Property<int?>("LastBazresi")
                        .HasColumnType("int");

                    b.Property<string>("NextBazresi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("T_AdminsBackups_ID")
                        .HasColumnType("bigint");

                    b.Property<int?>("T_Item_Bazresi_Id")
                        .HasColumnType("int");

                    b.Property<int?>("T_L_Ferekans_Bazresi_Id")
                        .HasColumnType("int");

                    b.Property<int?>("T_L_Ferekans_Bazresi_Title")
                        .HasColumnType("int");

                    b.HasKey("ID_Ferekans_Item_Bazresi");

                    b.ToTable("FerekansItem");
                });

            modelBuilder.Entity("BazresiApi.Models.T_Item_Bazresi", b =>
                {
                    b.Property<long>("ID_Item_Bazresi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID_Item_Bazresi"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ferekans_Bazresi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ID_Item_BazresiApp")
                        .HasColumnType("int");

                    b.Property<int?>("Is_Active")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Onvan_Item")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ravesh_Bazresi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SalSakht")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sarparast_Vahed")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Sazande")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Shomare_Shenasayi")
                        .HasColumnType("int");

                    b.Property<long?>("T_AdminsBackups_ID")
                        .HasColumnType("bigint");

                    b.Property<int?>("T_L_Class_Item_Id")
                        .HasColumnType("int");

                    b.Property<string>("T_L_Title_Zir_Class_Item")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("T_L_Titles_Class_Item")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("T_L_Titles_Vahed")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("T_L_Vahed_Id")
                        .HasColumnType("int");

                    b.Property<int?>("T_L_Zir_Class_Item_Id")
                        .HasColumnType("int");

                    b.HasKey("ID_Item_Bazresi");

                    b.ToTable("ItemBazresi");
                });

            modelBuilder.Entity("BazresiApi.Models.T_L_Class_Item", b =>
                {
                    b.Property<long>("ID_Class_Item")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID_Class_Item"));

                    b.Property<int?>("ID_Class_ItemApp")
                        .HasColumnType("int");

                    b.Property<int?>("Is_Active")
                        .HasColumnType("int");

                    b.Property<long?>("T_AdminsBackups_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("Titles_Class_Item")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID_Class_Item");

                    b.ToTable("ClassItem");
                });

            modelBuilder.Entity("BazresiApi.Models.T_L_Ferekans_Bazresi", b =>
                {
                    b.Property<long>("ID_Ferekans_Bazresi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID_Ferekans_Bazresi"));

                    b.Property<int?>("ID_Ferekans_BazresiApp")
                        .HasColumnType("int");

                    b.Property<int?>("Is_Active")
                        .HasColumnType("int");

                    b.Property<long?>("T_AdminsBackups_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("Title_Ferekans_Bazresi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID_Ferekans_Bazresi");

                    b.ToTable("FerekansBazresi");
                });

            modelBuilder.Entity("BazresiApi.Models.T_L_Ravesh_Bazresi", b =>
                {
                    b.Property<long>("ID_Ravesh_Bazresi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID_Ravesh_Bazresi"));

                    b.Property<int?>("ID_Ravesh_BazresiApp")
                        .HasColumnType("int");

                    b.Property<int?>("Is_Active")
                        .HasColumnType("int");

                    b.Property<long?>("T_AdminsBackups_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("Title_Ravesh_Bazresi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID_Ravesh_Bazresi");

                    b.ToTable("RaveshBazresi");
                });

            modelBuilder.Entity("BazresiApi.Models.T_L_SabegheKar", b =>
                {
                    b.Property<long>("ID_SabegheKar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID_SabegheKar"));

                    b.Property<int?>("ID_SabegheKarApp")
                        .HasColumnType("int");

                    b.Property<long?>("T_AdminsBackups_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("Title_SabegheKar")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_SabegheKar");

                    b.ToTable("SabegheKar");
                });

            modelBuilder.Entity("BazresiApi.Models.T_L_Sharh_Moshkelat", b =>
                {
                    b.Property<long>("ID_L_Sharh_Moshkelat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID_L_Sharh_Moshkelat"));

                    b.Property<int?>("ID_L_Sharh_MoshkelatApp")
                        .HasColumnType("int");

                    b.Property<long?>("T_AdminsBackups_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("Title_Sharh_Moshkelat")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID_L_Sharh_Moshkelat");

                    b.ToTable("SharhMoshkelat");
                });

            modelBuilder.Entity("BazresiApi.Models.T_L_Vahed", b =>
                {
                    b.Property<long>("ID_Vahed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID_Vahed"));

                    b.Property<int?>("ID_Soalat_CheckListApp")
                        .HasColumnType("int");

                    b.Property<int?>("Is_Active")
                        .HasColumnType("int");

                    b.Property<long?>("T_AdminsBackups_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("Titles_Vahed")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID_Vahed");

                    b.ToTable("Vahed");
                });

            modelBuilder.Entity("BazresiApi.Models.T_L_Vaziat_Ejra", b =>
                {
                    b.Property<long>("ID_Vaziat_Ejra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID_Vaziat_Ejra"));

                    b.Property<int?>("ID_Vaziat_EjraApp")
                        .HasColumnType("int");

                    b.Property<long?>("T_AdminsBackups_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("Title_Vaziat_Ejra")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID_Vaziat_Ejra");

                    b.ToTable("VaziatEjra");
                });

            modelBuilder.Entity("BazresiApi.Models.T_L_Zir_Class_Item", b =>
                {
                    b.Property<long>("ID_Zir_Class_Item")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID_Zir_Class_Item"));

                    b.Property<int?>("ID_Zir_Class_ItemApp")
                        .HasColumnType("int");

                    b.Property<int?>("Is_Active")
                        .HasColumnType("int");

                    b.Property<long?>("T_AdminsBackups_ID")
                        .HasColumnType("bigint");

                    b.Property<int?>("T_L_Class_Item_Id")
                        .HasColumnType("int");

                    b.Property<string>("Title_Zir_Class_Item")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID_Zir_Class_Item");

                    b.ToTable("ZirClassItem");
                });

            modelBuilder.Entity("BazresiApi.Models.T_Ravesh_Item_Bazresi", b =>
                {
                    b.Property<long>("ID_Ravesh_Item_Bazresi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID_Ravesh_Item_Bazresi"));

                    b.Property<int?>("ID_Ravesh_Item_BazresiApp")
                        .HasColumnType("int");

                    b.Property<int?>("Is_Active")
                        .HasColumnType("int");

                    b.Property<long?>("T_AdminsBackups_ID")
                        .HasColumnType("bigint");

                    b.Property<int?>("T_Item_Bazresi_Id")
                        .HasColumnType("int");

                    b.Property<int?>("T_L_Ravesh_Bazresi_Id")
                        .HasColumnType("int");

                    b.Property<string>("T_L_Ravesh_Bazresi_Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Ravesh_Item_Bazresi");

                    b.ToTable("RaveshItemBazresi");
                });

            modelBuilder.Entity("BazresiApi.Models.T_Sharh_Moshkelat_Bazresi", b =>
                {
                    b.Property<long>("ID_Sharh_Moshkelat_Bazresi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID_Sharh_Moshkelat_Bazresi"));

                    b.Property<int?>("ID_Sharh_Moshkelat_BazresiApp")
                        .HasColumnType("int");

                    b.Property<int?>("Is_Temp")
                        .HasColumnType("int");

                    b.Property<long?>("T_AdminsBackups_ID")
                        .HasColumnType("bigint");

                    b.Property<int?>("T_Bazresi_Azmon_Id")
                        .HasColumnType("int");

                    b.Property<int?>("T_Bazresi_CheckList_OK_Id")
                        .HasColumnType("int");

                    b.Property<int?>("T_Item_Bazresi_Id")
                        .HasColumnType("int");

                    b.Property<string>("T_L_Title_Sharh_Moshkelat")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("T_Soalat_CheckList_Onvan_Soal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID_Sharh_Moshkelat_Bazresi");

                    b.ToTable("SharhMoshkelatBazresi");
                });

            modelBuilder.Entity("BazresiApi.Models.T_Soalat_CheckList", b =>
                {
                    b.Property<long>("ID_Soalat_CheckList")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID_Soalat_CheckList"));

                    b.Property<string>("DateCreate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ID_Soalat_CheckListApp")
                        .HasColumnType("int");

                    b.Property<int?>("Is_Active")
                        .HasColumnType("int");

                    b.Property<string>("Marja_Porsesh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Onvan_Soal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("T_AdminsBackups_ID")
                        .HasColumnType("bigint");

                    b.Property<int?>("T_CheckList_Id")
                        .HasColumnType("int");

                    b.Property<int?>("T_Ferekans_Item_Bazresi_Id")
                        .HasColumnType("int");

                    b.Property<string>("T_Ferekans_Item_Bazresi_Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("T_Item_Bazresi_Id")
                        .HasColumnType("int");

                    b.Property<string>("Tozihat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Soalat_CheckList");

                    b.ToTable("SoalatCheckList");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BazresiApi.Customized.CustomUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BazresiApi.Customized.CustomUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BazresiApi.Customized.CustomUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BazresiApi.Customized.CustomUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
